import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

// Define the metadata for the page
export const metadata: Metadata = {
  title: "Notion Clone",
  description: "Generated by create next app",
};

// Define the default layout for the page
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          {/* Sidebar */}
          <div>
            <SidebarProvider>
              <AppSidebar />
              <div className="flex-1 p-4 bg-gray-100 overflow-y-auto scrollbar-hide">
                <main>
                  <SidebarTrigger />
                  <Header />
                  {children}
                </main>
              </div>
            </SidebarProvider>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
